---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: curl
  name: curl
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - 'sleep 60; while true; do echo "$(curl nginx:8080)"; sleep 120; done'
    image: alpine/curl
    name: curl
    resources:
      requests:
        cpu: 10m
        memory: 8Mi
      limits:
        cpu: 50m
        memory: 64Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
